"""add table player_profiles

Revision ID: 4a87515c3a40
Revises: 827dd1ea8104
Create Date: 2026-09-03 13:15:09.805612

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a87515c3a40'
down_revision: Union[str, Sequence[str], None] = '827dd1ea8104'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('player_profiles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('xp', sa.Integer(), nullable=False),
    sa.Column('soft_currency', sa.Integer(), nullable=False),
    sa.Column('hard_currency', sa.Integer(), nullable=False),
    sa.Column('avatar_id', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('player_profiles')
    # ### end Alembic commands ###
